# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  sln: '$(Build.Repository.LocalPath)\src\Microsoft.DotnetOrg.Policies.sln'
  outDir: '$(Build.ArtifactStagingDirectory)\'
  policop: '$(Pipeline.Workspace)\drop\policop.exe'
  cachePath: '$(Build.ArtifactStagingDirectory)'
  violationsPath: '$(Build.ArtifactStagingDirectory)\dotnet.csv'

jobs:
- job: build
  displayName: Build
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(sln)'
  - task: MSBuild@1
    inputs:
      solution: '$(sln)'
      msbuildArguments: '/p:OutDir=$(outDir)'
  - task: PublishBuildArtifacts@1
    condition: eq(variables['system.pullrequest.isfork'], false)
- job:
  dependsOn: build
  displayName: Run policop
  timeoutInMinutes: 240
  condition: |
    and(
      eq(variables['Build.DefinitionName'], 'dotnet-org-policy-check-run'),
      or(
        eq(variables['Build.Reason'], 'Schedule'),
        eq(variables['Build.Reason'], 'Manual')
      )
    )
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
  - script: $(policop) cache-org --org dotnet --with-ms-links --github-token $(GitHubToken) --ospo-token $(OspoToken)
    displayName: Cache dotnet
  - script: $(policop) cache-org --org aspnet --with-ms-links --github-token $(GitHubToken) --ospo-token $(OspoToken)
    displayName: Cache aspnet
  - script: $(policop) cache-org --org xamarin --with-ms-links --github-token $(GitHubToken) --ospo-token $(OspoToken)
    displayName: Cache xamarin
  - script: $(policop) cache-org --org xamarinhq --with-ms-links --github-token $(GitHubToken) --ospo-token $(OspoToken)
    displayName: Cache xamarinhq
  - script: $(policop) cache-org --org mono --with-ms-links --github-token $(GitHubToken) --ospo-token $(OspoToken)
    displayName: Cache mono
  - script: $(policop) cache-export -o $(cachePath)
    displayName: Export cache
  - script: $(policop) check --org dotnet -o $(violationsPath) --policy-repo dotnet/org-policy-violations --update-issues --github-token $(GitHubToken)
    displayName: Check dotnet
  - script: $(policop) cache-clear -f
    displayName: Clear org cache
  - task: PublishBuildArtifacts@1
